### ISSUE TITLE
"game_day" doesn't appear correct after scrape_statcast()

### ISSUE THREAD

**Issue by Masashi-Yok** [pontsuyu/statcastr#1]
After `scrape_statcast()`, I wrote in SQLite and cheked the data. Then I found that "game_day" does not appear correct.
For example, when I scraped the data for 2019-04-07, "game_day" was "17993.0" on SQLite.

**Comment by pontsuyu** [comment]
This problem is not statcastr package's fault.
Please refer to this. https://github.com/r-dbi/RSQLite/issues/237


Here is the solution for the moment：
```r
library(statcastr)
library(tidyverse)
tmp <- scrape_statcast("2019-04-07", "2019-04-08", "pitcher")
tmp$game_date <- as.character(tmp$game_date)

db <- src_sqlite("test.sqlite3", create = T)
copy_to(db, tmp)
```
